# Generated by Django 5.0.1 on 2024-01-12 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='reels',
        ),
    ]
