# Generated by Django 5.0.1 on 2024-01-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_pre_wedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_wedding',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
