# Generated by Django 5.0.1 on 2024-01-13 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_pre_wedding_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pre_wedding',
            old_name='view',
            new_name='views',
        ),
    ]
