# Generated by Django 5.0.1 on 2024-01-13 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_rename_view_pre_wedding_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pre_wedding',
            old_name='couple',
            new_name='title',
        ),
    ]
