# Generated by Django 5.0.1 on 2024-01-13 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0006_rename_couple_pre_wedding_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pre_wedding',
            old_name='poster',
            new_name='file',
        ),
    ]
