# Generated by Django 5.0.1 on 2024-01-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0007_rename_poster_pre_wedding_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default='0001-01-01')),
                ('file', models.FileField(upload_to='assets/images/wedding_poster')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='pre_wedding',
            name='date',
            field=models.DateField(default='0001-01-01'),
        ),
    ]
