# Generated by Django 5.0.1 on 2024-01-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0009_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='file',
            field=models.FileField(upload_to='assets/images/events_poster'),
        ),
    ]
