# Generated by Django 5.0.1 on 2024-01-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0011_banner_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
