# Generated by Django 5.0.1 on 2024-01-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0012_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='wedding_date',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
