# Generated by Django 5.0.1 on 2024-01-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0013_client_wedding_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='wedding_date',
            field=models.DateField(blank=True, default='0001-01-01', null=True),
        ),
    ]
