# Generated by Django 5.0.1 on 2024-01-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0014_alter_client_wedding_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='wedding_date',
            new_name='main_wedding_date',
        ),
    ]
