# Generated by Django 5.0.1 on 2024-01-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0017_client_wedding_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='wedding_address',
            new_name='wedding_venue',
        ),
    ]
