# Generated by Django 5.0.1 on 2024-01-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0018_rename_wedding_address_client_wedding_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_picture',
            field=models.FileField(default='', upload_to='assets/images/user/profile-picture'),
            preserve_default=False,
        ),
    ]
