# Generated by Django 5.0.1 on 2024-01-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0019_client_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='profile_picture',
            new_name='profile',
        ),
    ]
