# Generated by Django 5.0.1 on 2024-01-24 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0024_service_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='shoot_date',
            field=models.DateField(blank=True, default='0001-01-01', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='console.additionalservice'),
            preserve_default=False,
        ),
    ]
