# Generated by Django 5.0.1 on 2024-01-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0026_alter_booking_additional_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='segment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
