# Generated by Django 5.0.1 on 2024-01-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0027_additionalservice_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservice',
            name='segment',
            field=models.CharField(max_length=100),
        ),
    ]
