# Generated by Django 5.0.1 on 2024-01-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0028_alter_additionalservice_segment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='additional_service',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_service',
            field=models.ManyToManyField(to='console.additionalservice'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ManyToManyField(to='console.service'),
        ),
    ]
