# Generated by Django 5.0.1 on 2024-01-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0030_remove_booking_additional_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_service',
            field=models.ManyToManyField(to='console.additionalservice'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ManyToManyField(to='console.service'),
        ),
    ]
