# Generated by Django 5.0.1 on 2024-01-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0032_remove_booking_additional_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_service',
            field=models.ManyToManyField(to='console.additionalservice'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ManyToManyField(to='console.service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='shoot_date',
            field=models.DateField(default='0001-01-01'),
            preserve_default=False,
        ),
    ]
