# Generated by Django 5.0.1 on 2024-01-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0033_booking_additional_service_booking_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='segment',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
