# Generated by Django 5.0.1 on 2024-01-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0034_service_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='applicable',
            field=models.CharField(default='day', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='applicable',
            field=models.CharField(default='complete_shoot', max_length=100, null=True),
        ),
    ]
