# Generated by Django 5.0.1 on 2024-01-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0035_additionalservice_applicable_service_applicable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalservice',
            old_name='applicable',
            new_name='charges_application',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='applicable',
            new_name='charges_application',
        ),
    ]
