# Generated by Django 5.0.1 on 2024-01-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0036_rename_applicable_additionalservice_charges_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservice',
            name='charges_application',
            field=models.CharField(default='per_day', max_length=100, null=True),
        ),
    ]
