# Generated by Django 5.0.1 on 2024-01-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0040_payments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_wedding',
            name='video_link',
            field=models.FileField(default='', upload_to='assets/video/pre_wedding'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pre_wedding',
            name='video_youtube_link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pre_wedding',
            name='youtube',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
