# Generated by Django 5.0.1 on 2024-01-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0042_rename_file_pre_wedding_cover_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_wedding',
            name='video_link',
            field=models.FileField(null=True, upload_to='assets/video/pre_wedding'),
        ),
        migrations.AlterField(
            model_name='pre_wedding',
            name='video_youtube_link',
            field=models.TextField(null=True),
        ),
    ]
