# Generated by Django 5.0.1 on 2024-01-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0043_alter_pre_wedding_video_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pre_wedding',
            old_name='youtube',
            new_name='is_youtube_video',
        ),
    ]
