# Generated by Django 5.0.1 on 2024-01-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0045_rename_file_wedding_cover_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='file',
            new_name='cover_picture',
        ),
        migrations.AddField(
            model_name='events',
            name='is_youtube_video',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='video_link',
            field=models.FileField(null=True, upload_to='assets/video/events'),
        ),
        migrations.AddField(
            model_name='events',
            name='video_youtube_link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='video_link',
            field=models.FileField(null=True, upload_to='assets/video/wedding'),
        ),
    ]
