# Generated by Django 5.0.1 on 2024-01-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0047_alter_client_contact_number_alter_events_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_wedding',
            name='video_link',
            field=models.FileField(blank=True, default='', null=True, upload_to='assets/video/pre_wedding'),
        ),
    ]
