# Generated by Django 5.0.1 on 2024-01-29 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0049_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='console.payments'),
            preserve_default=False,
        ),
    ]
