# Generated by Django 5.0.1 on 2024-01-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0053_alter_client_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile',
            field=models.FileField(blank=True, default='/assets/images/user/profile-picture/user.png', null=True, upload_to='assets/images/user/profile-picture'),
        ),
    ]
