# Generated by Django 5.0.1 on 2024-02-03 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0055_drp_booking_status_booking_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_ShootDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='console.drp_booking_status'),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='shoot_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='shoot_date',
            field=models.ManyToManyField(to='console.booking_shootdate'),
        ),
    ]
