# Generated by Django 5.0.1 on 2024-02-03 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0056_booking_shootdate_alter_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.service')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ManyToManyField(to='console.package'),
        ),
    ]
