# Generated by Django 5.0.1 on 2024-02-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0057_remove_booking_service_package_booking_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='service',
        ),
        migrations.AddField(
            model_name='package',
            name='service',
            field=models.ManyToManyField(to='console.service'),
        ),
    ]
