# Generated by Django 5.0.1 on 2024-02-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0061_remove_booking_package_booking_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_shootdate',
            name='additional_service',
            field=models.ManyToManyField(to='console.additionalservice'),
        ),
        migrations.AddField(
            model_name='booking_shootdate',
            name='event_type',
            field=models.CharField(default='wedding', max_length=50),
            preserve_default=False,
        ),
    ]
