# Generated by Django 5.0.1 on 2024-02-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0062_booking_shootdate_additional_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pre_wedding_shoot',
            field=models.BooleanField(default=False),
        ),
    ]
