# Generated by Django 5.0.1 on 2024-02-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0063_booking_pre_wedding_shoot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='additional_service',
        ),
    ]
