# Generated by Django 5.0.1 on 2024-02-13 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0064_remove_booking_additional_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='additional_service_bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='console.additionalservice')),
            ],
        ),
    ]
