# Generated by Django 5.0.1 on 2024-02-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0065_additional_service_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='additional_service_bookings',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking_shootdate',
            name='additional_service',
            field=models.ManyToManyField(to='console.additional_service_bookings'),
        ),
    ]
