# Generated by Django 5.0.1 on 2024-02-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0066_additional_service_bookings_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additional_service_bookings',
            old_name='quantity',
            new_name='count',
        ),
    ]
