# Generated by Django 5.0.1 on 2024-02-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0067_rename_quantity_additional_service_bookings_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pre_wedding_shoot',
        ),
    ]
