# Generated by Django 5.0.1 on 2024-02-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0068_remove_booking_pre_wedding_shoot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalservice',
            name='charges_application',
        ),
        migrations.RemoveField(
            model_name='service',
            name='charges_application',
        ),
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
