# Generated by Django 5.0.1 on 2024-02-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0070_alter_payments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
