# Generated by Django 5.0.1 on 2024-02-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0072_alter_booking_discount_alter_booking_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_price',
        ),
    ]
