# Generated by Django 5.0.1 on 2024-02-20 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0074_remove_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='segment',
        ),
    ]
