# Generated by Django 5.0.1 on 2024-02-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0077_service_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='status',
            new_name='trash',
        ),
    ]
