# Generated by Django 5.0.1 on 2024-02-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0078_rename_status_service_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
