# Generated by Django 5.0.1 on 2024-02-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0081_additionalservice_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
