# Generated by Django 5.0.1 on 2024-02-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0082_package_trash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('file', models.FileField(upload_to='assets/image/showcase_image')),
            ],
        ),
    ]
