# Generated by Django 5.0.1 on 2024-02-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0083_showcase_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase_images',
            name='file',
            field=models.FileField(upload_to='assets/images/showcase_image'),
        ),
    ]
