# Generated by Django 5.0.1 on 2024-02-23 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0084_alter_showcase_images_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='main_wedding_date',
            new_name='wedding_date',
        ),
    ]
