# Generated by Django 5.0.1 on 2024-02-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0085_rename_main_wedding_date_client_wedding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_token',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
