# Generated by Django 5.0.1 on 2024-02-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0088_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
