# Generated by Django 5.0.1 on 2024-03-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0089_team_member_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateField(default='0001-01-01'),
        ),
    ]
