# Generated by Django 5.0.1 on 2024-03-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0091_alter_client_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
