# Generated by Django 5.0.1 on 2024-03-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0092_alter_client_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='created_at',
            field=models.DateField(default='0001-01-01'),
        ),
        migrations.AddField(
            model_name='pre_wedding',
            name='created_at',
            field=models.DateField(default='0001-01-01'),
        ),
        migrations.AddField(
            model_name='reels',
            name='created_at',
            field=models.DateField(default='0001-01-01'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='created_at',
            field=models.DateField(default='0001-01-01'),
        ),
    ]
