# Generated by Django 5.0.1 on 2024-04-01 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0094_alter_events_created_at_alter_pre_wedding_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='booking',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='console.booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='console.client'),
        ),
    ]
