# Generated by Django 5.0.1 on 2024-04-01 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0095_client_booking_alter_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='console.payments')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='qoutation',
            field=models.ManyToManyField(to='console.quotation'),
        ),
    ]
