# Generated by Django 5.0.1 on 2024-04-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0096_quotation_client_qoutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='additional_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
