# Generated by Django 5.0.1 on 2024-04-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0097_quotation_additional_price_quotation_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='qoutation',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
    ]
