# Generated by Django 5.0.1 on 2024-04-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0099_deliverables'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deliverables',
            field=models.ManyToManyField(to='console.deliverables'),
        ),
        migrations.AlterField(
            model_name='deliverables',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
