# Generated by Django 5.0.1 on 2024-04-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0100_client_deliverables_alter_deliverables_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverables',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
