# Generated by Django 5.0.1 on 2024-04-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0101_alter_deliverables_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms_Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('trash', models.BooleanField(default=False)),
            ],
        ),
    ]
