# Generated by Django 5.0.1 on 2024-04-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0102_terms_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='deliverables',
        ),
        migrations.AddField(
            model_name='booking',
            name='deliverables',
            field=models.ManyToManyField(to='console.deliverables'),
        ),
        migrations.AddField(
            model_name='booking',
            name='terms_conditions',
            field=models.ManyToManyField(to='console.terms_conditions'),
        ),
    ]
