# Generated by Django 5.0.1 on 2024-04-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0103_remove_client_deliverables_booking_deliverables_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='deliverables',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='terms_conditions',
        ),
    ]
