# Generated by Django 5.0.1 on 2024-04-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0104_remove_booking_deliverables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
