# Generated by Django 5.0.1 on 2024-04-17 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0106_payments_payment_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default='0001-01-01', null=True)),
                ('note', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='fund_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default='0001-01-01', null=True)),
                ('note', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('booking', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='console.booking')),
            ],
        ),
        migrations.AddField(
            model_name='team_member',
            name='fund',
            field=models.ManyToManyField(to='console.fund_history'),
        ),
        migrations.AddField(
            model_name='team_member',
            name='Payments',
            field=models.ManyToManyField(to='console.payments_history'),
        ),
    ]
