# Generated by Django 5.0.1 on 2024-04-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0107_payments_history_fund_history_team_member_fund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund_history',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
