# Generated by Django 5.0.1 on 2024-04-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0108_alter_fund_history_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_member',
            name='Payments',
        ),
    ]
