# Generated by Django 5.0.1 on 2024-04-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0109_remove_team_member_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='payments',
            field=models.ManyToManyField(to='console.payments_history'),
        ),
    ]
